<?php
	SESSION_START();
php?>
<CENTER>
<?php
	require_once "inc/sql.php";
	connect_valid();

ECHO "
<TABLE BORDER=0>
<TR><TD COLSPAN=3 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#BBBBBB'>罷免工作人員管理及罷免文書處理系統</TD></TR>";
IF($_GET['ACT']=="LOGIN")
{
	ECHO "<TR><TD STYLE='BACKGROUND-COLOR:#EEEEEE;TEXT-ALIGN:CENTER;WIDTH:300'>";
	IF($_SESSION['SID']=="")
	{
		$QUERY_STRING="SELECT * FROM STAFF_INFO WHERE NICKNAME='".$_POST['NICKNAME']."' AND PASSWORD=PASSWORD('".$_POST['PASSWORD']."')";
		IF(MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING))==1)
		{
			ECHO "<BR>登入成功<BR>";
			$DATA=MYSQL_FETCH_ARRAY($RESULT);
			$_SESSION['SID']=$DATA['staff_id'];
			$_SESSION['LEVEL']=$DATA['level'];
			$_SESSION['NICKNAME']=$DATA['nickname'];
			$_SESSION['DISTRICT_ID']=$DATA['elect_district_id'];
		}
		ELSE
		{
			ECHO "<BR>登入失敗<BR><BR>
			<INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php' VALUE='回上一頁' STYLE='FONT-SIZE:16'><BR>";
		}
	}
	
	IF($_SESSION['SID']!="")
	{
		ECHO "<BR>";
		ECHO "<INPUT TYPE=BUTTON ONCLICK=location.href='processing_form.php?ACT=GO' VALUE='進入文書處理頁面' STYLE='FONT-SIZE:16;WIDTH:150'><BR><BR>";
		ECHO "<INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php?ACT=CPWD' VALUE='進入密碼修改頁面' STYLE='FONT-SIZE:16;WIDTH:150'><BR><BR>";
		IF($_SESSION['LEVEL']=='admin'||$_SESSION['LEVEL']=='reg_admin')
		{
			ECHO "<FORM ACTION=form_qrcode_generator_admin.php?DDID=".$DATA['elect_district_id']." METHOD=POST TARGET=_blank>
				<INPUT TYPE=SUBMIT VALUE='印空白表單及標籤' STYLE='FONT-SIZE:16;WIDTH:150'>
				</FORM>";
			ECHO "<INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php?ACT=STFMGR' VALUE='管理工作人員頁面' STYLE='FONT-SIZE:16;WIDTH:150'><BR><BR>";
		}
		ELSE
		{
			ECHO "<FORM ACTION=form_qrcode_generator.php?DDID=".$DATA['elect_district_id']." METHOD=POST TARGET=_blank>
				<INPUT TYPE=SUBMIT VALUE='印空白表單及標籤' STYLE='FONT-SIZE:16;WIDTH:150'>
				</FORM>";
		}
		ECHO "<INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php?ACT=LOGOUT' VALUE='登出' STYLE='FONT-SIZE:16;WIDTH:150'><BR>";
	}
	ECHO "<BR>";
	ECHO "</TD></TR>";
}
ELSE IF($_GET['ACT']=="STFMGR")
{
	ECHO "<TR><TD STYLE='BACKGROUND-COLOR:#EEEEEE;TEXT-ALIGN:CENTER;'>";
	ECHO "<TABLE BORDER=0>";
	ECHO "<TR STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'><TD COLSPAN=5>工作人員列表</TD><TD><INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php?ACT=ADDSTF' VALUE='新增'></TD></TR>";
	$QUERY_STRING="SELECT * FROM STAFF_INFO AS SI LEFT JOIN DISTRICT_DATA AS DD ON SI.ELECT_DISTRICT_ID=DD.DISTRICT_ID WHERE STAFF_ID>1";
	IF($_SESSION[LEVEL]=='reg_admin')
		$QUERY_STRING.=" AND ELECT_DISTRICT_ID='".$_SESSION['DISTRICT_ID']."'";
	$NO_OF_DATA=MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING));
	IF($NO_OF_DATA>0)
	{
		ECHO "<TR STYLE='BACKGROUND-COLOR:#DDDDDD;TEXT-ALIGN:CENTER'><TD STYLE='WIDTH:40'>No.</TD><TD STYLE='WIDTH:100'>代號</TD><TD STYLE='WIDTH:100'>等級</TD><TD STYLE='WIDTH:200'>選區</TD><TD STYLE='WIDTH:150'>E-mail</TD><TD STYLE='WIDTH:150'>處理動作</TD></TR>";
		FOR($SEED=0;$SEED<$NO_OF_DATA;$SEED++)
		{
			$DATA=MYSQL_FETCH_ARRAY($RESULT);
			IF($SEED%2==1)
				ECHO "<TR STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDFFDD'>";
			ELSE
				ECHO "<TR STYLE='TEXT-ALIGN:CENTER'>";
			ECHO "<TD STYLE='BACKGROUND-COLOR:#DDDDDD;'>".($SEED+1)."</TD><TD>".$DATA['nickname']."</TD><TD>";
//			IF($DATA['level']=='admin')
			IF($DATA['level']=='admin')
				ECHO "管理員";
			ELSE IF($DATA['level']=='reg_admin')
				ECHO "區域管理員";
			ELSE
				ECHO "一般";
			ECHO "</TD><TD>".$DATA['district_name']."．".$DATA['district_legislator']."</TD><TD>".$DATA['email']."</TD><TD>";
			ECHO "<INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php?ACT=MODSTF&SID=".$DATA['staff_id']."' VALUE='變更'>";
			IF(strtoupper($_SESSION['NICKNAME'])!=strtoupper($DATA['nickname']))
			{
				ECHO "<INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php?ACT=DELSTF&SID=".$DATA['staff_id']."' VALUE='刪除'>";
			}
			ECHO "</TD></TR>";
		}
		ECHO "<TR><TD ALIGN=CENTER COLSPAN=6>
				<HR>
				<INPUT TYPE=BUTTON ONCLICK=location.href='processing_system.php?ACT=LOGIN' VALUE='回上一頁' STYLE='FONT-SIZE:16;WIDTH:150'>
				</TD></TR>";
	}
	ECHO "</TABLE>";
	ECHO "</TD></TR>";
}
ELSE IF($_GET['ACT']=="DELSTFEXE"||$_GET['ACT']=="MODSTFEXE"||$_GET['ACT']=="ADDSTFEXE")
{
	ECHO "<TR><TD STYLE='BACKGROUND-COLOR:#EEEEEE;TEXT-ALIGN:CENTER;WIDTH:300'>";
	$QUERY_STRING="SELECT * FROM STAFF_INFO WHERE NICKNAME='".$_POST['NICKNAME']."' AND PASSWORD=PASSWORD('".$_POST['PASSWORD']."') AND LEVEL='admin'";
	IF(MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING))==1)
	{
		$DATA=MYSQL_FETCH_ARRAY($RESULT);
		$ADMIN_ID=$DATA['staff_id'];
		IF($_GET['ACT']=="ADDSTFEXE")
		{
			ECHO "<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>新增工作人員<SPAN STYLE='COLOR:RED'>&nbsp;".$DATA['USERNAME']."&nbsp;</SPAN>處理結果</TD></TR>";
			ECHO "<TR><TD ALIGN=CENTER STYLE='BACKGROUND-COLOR:#DDDDDD'><BR>";
			IF($_POST['USERNAME']!=""&&$_POST['STFEMAIL']!=""&&$_POST['STFPASSWORD']!="")
			{
				IF($_POST['DISTRICT_ID']=="")
					$QUERY_STRING="INSERT INTO STAFF_INFO(NICKNAME,EMAIL,PASSWORD,LEVEL)VALUES('".$_POST['USERNAME']."','".$_POST['STFEMAIL']."',PASSWORD('".$_POST['STFPASSWORD']."'),'".$_POST['LEVEL']."')";
				ELSE
					$QUERY_STRING="INSERT INTO STAFF_INFO(NICKNAME,EMAIL,PASSWORD,LEVEL,ELECT_DISTRICT_ID)VALUES('".$_POST['USERNAME']."','".$_POST['STFEMAIL']."',PASSWORD('".$_POST['STFPASSWORD']."'),'".$_POST['LEVEL']."','".$_POST['DISTRICT_ID']."')";
				IF(MYSQL_QUERY($QUERY_STRING))
				{
					ECHO "新增成功！";
					ECHO "<FORM ACTION=processing_system.php?ACT=STFMGR METHOD=POST>
						<INPUT TYPE=HIDDEN NAME=NICKNAME VALUE='".$_POST['NICKNAME']."'>
						<INPUT TYPE=HIDDEN NAME=PASSWORD VALUE='".$_POST['PASSWORD']."'>
						<INPUT TYPE=SUBMIT VALUE='回工作人員列表' STYLE='FONT-SIZE:16;WIDTH:150'>
						</FORM>";
				}
				ELSE
				{
					ECHO "新增失敗！<BR><BR><INPUT TYPE=BUTTON ONCLICK=history.go(-2) VALUE='回工作人員列表'><BR><BR>";
				}
			}
			ELSE
			{
				ECHO "新增失敗，所有欄位皆須填寫！<BR><BR><INPUT TYPE=BUTTON ONCLICK=history.go(-1) VALUE='回上一頁'><BR><BR>";
			}
		}
		ELSE
		{
			$QUERY_STRING="SELECT * FROM STAFF_INFO WHERE STAFF_ID='".$_GET['SID']."'";
			IF(MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING))==1)
			{
				$DATA=MYSQL_FETCH_ARRAY($RESULT);
				IF($_GET['ACT']=="DELSTFEXE")
				{
					ECHO "<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>刪除工作人員<SPAN STYLE='COLOR:RED'>&nbsp;".$DATA['nickname']."&nbsp;</SPAN>處理結果</TD></TR>";
				}
				ELSE
				{
					ECHO "<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>變更工作人員資料<SPAN STYLE='COLOR:RED'>&nbsp;".$DATA['nickname']."&nbsp;</SPAN>處理結果</TD></TR>";
				}
				ECHO "<TR><TD ALIGN=CENTER STYLE='BACKGROUND-COLOR:#DDDDDD'><BR>";
				IF($_GET['ACT']=="DELSTFEXE")
				{
					$QUERY_STRING="DELETE FROM STAFF_INFO WHERE STAFF_ID='".$_GET['SID']."'";
				}
				ELSE IF($_GET['ACT']=="MODSTFEXE")
				{
					$QUERY_STRING="UPDATE STAFF_INFO SET EMAIL='".$_POST['EMAIL']."'";
					IF($ADMIN_ID!=$_GET['SID'])
						$QUERY_STRING.=",LEVEL='".$_POST['LEVEL']."'";
					IF($_POST['STFPASSWORD']!="")
						$QUERY_STRING.=",PASSWORD=PASSWORD('".$_POST['STFPASSWORD']."')";
					IF($_POST['DISTRICT_ID']!="")
						$QUERY_STRING.=",ELECT_DISTRICT_ID='".$_POST['DISTRICT_ID']."'";
					$QUERY_STRING.=" WHERE STAFF_ID='".$_GET['SID']."'";
				}
				//ECHO $QUERY_STRING;
				IF(MYSQL_QUERY($QUERY_STRING))
				{
					ECHO "處理成功！";
					ECHO "<FORM ACTION=processing_system.php?ACT=STFMGR METHOD=POST>
						<INPUT TYPE=HIDDEN NAME=NICKNAME VALUE='".$_POST['NICKNAME']."'>
						<INPUT TYPE=HIDDEN NAME=PASSWORD VALUE='".$_POST['PASSWORD']."'>
						<INPUT TYPE=SUBMIT VALUE='回工作人員列表' STYLE='FONT-SIZE:16;WIDTH:150'>
						</FORM>";
				}
				ELSE
				{
					ECHO "處理失敗！<BR><BR><INPUT TYPE=BUTTON ONCLICK=history.go(-2) VALUE='回工作人員列表'><BR><BR>";
				}
			}
			ELSE
			{
				ECHO "<BR>查無此資料<BR><BR><INPUT TYPE=BUTTON ONCLICK=history.go(-2) VALUE='回工作人員列表'><BR><BR>";
			}
		}
	}
	ELSE
	{
		ECHO "<BR>管理者資料輸入錯誤<BR><BR><INPUT TYPE=BUTTON ONCLICK=history.go(-1) VALUE='回上頁重新輸入'><INPUT TYPE=BUTTON ONCLICK=history.go(-2) VALUE='回工作人員列表'><BR><BR>";
	}
	ECHO "</TD></TR>";
}
ELSE IF($_GET['ACT']=="DELSTF"||$_GET['ACT']=="MODSTF"||$_GET['ACT']=="ADDSTF")
{
	ECHO "<TR><TD STYLE='BACKGROUND-COLOR:#EEEEEE;TEXT-ALIGN:CENTER;'>";
	IF($_GET['ACT']=="ADDSTF")
	{
		ECHO "
		<TABLE BORDER=0 STYLE='BACKGROUND-COLOR:#EEEEEE;WIDTH:100%'>
			<FORM ACTION=processing_system.php?ACT=".$_GET['ACT']."EXE&SID=".$_GET['SID']." METHOD=POST>";
			ECHO "<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>新增工作人員資料</TD></TR>
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>登入名稱</TD><TD><INPUT TYPE=TEXT NAME=USERNAME STYLE='WIDTH:250;FONT-SIZE:16'></TD></TR>
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>電子信箱</TD><TD><INPUT TYPE=TEXT NAME=STFEMAIL STYLE='WIDTH:250;FONT-SIZE:16'></TD></TR>
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>登入密碼</TD><TD><INPUT TYPE=TEXT NAME=STFPASSWORD STYLE='WIDTH:250;FONT-SIZE:16'></TD></TR>";
			IF($_SESSION['LEVEL']=='admin')
				ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>等　　級</TD><TD><INPUT TYPE=RADIO NAME=LEVEL VALUE='normal' CHECKED>一般<INPUT TYPE=RADIO NAME=LEVEL VALUE='admin'>管理員<INPUT TYPE=RADIO NAME=LEVEL VALUE='reg_admin'>地區管理員</TD></TR>";
			ELSE IF($_SESSION['LEVEL']=='reg_admin')
				ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>等　　級</TD><TD><INPUT TYPE=RADIO NAME=LEVEL VALUE='normal' CHECKED>一般<INPUT TYPE=RADIO NAME=LEVEL VALUE='reg_admin'>地區管理員</TD></TR>";
			ECHO "
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>選　　區</TD><TD>";
			IF($_SESSION[LEVEL]=='admin')
				displayDistrict("0");
			ELSE IF($_SESSION[LEVEL]=='reg_admin')
				displayDistrictRestricted($_SESSION[DISTRICT_ID]);
			ECHO "</TD></TR>
			<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>請輸入管理者代號及密碼</TD></TR>
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>管理者名稱</TD><TD><INPUT TYPE=TEXT NAME=NICKNAME STYLE='WIDTH:150;FONT-SIZE:16'></TD></TR>
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>管理者密碼</TD><TD><INPUT TYPE=PASSWORD NAME=PASSWORD STYLE='WIDTH:150;FONT-SIZE:16' VALUE=''></TD></TR>
			<TR><TD COLSPAN=2 ALIGN=CENTER><INPUT TYPE=BUTTON ONCLICK=history.go(-1) VALUE='取消'><INPUT TYPE=SUBMIT VALUE='新增'></TD></TR>
			</FORM>
		</TABLE>";
	}
	ELSE
	{
		$QUERY_STRING="SELECT * FROM STAFF_INFO WHERE STAFF_ID='".$_GET['SID']."'";
		IF(MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING))==1)
		{
			$DATA=MYSQL_FETCH_ARRAY($RESULT);
			ECHO "
			<TABLE BORDER=0 STYLE='BACKGROUND-COLOR:#EEEEEE;WIDTH:100%'>
				<FORM ACTION=processing_system.php?ACT=".$_GET['ACT']."EXE&SID=".$_GET['SID']." METHOD=POST>";
			IF($_GET['ACT']=="DELSTF")
			{
				ECHO "<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>刪除工作人員<SPAN STYLE='COLOR:RED'>&nbsp;".$DATA['nickname']."</SPAN></TD></TR>";
			}
			ELSE IF($_GET['ACT']=="MODSTF")
			{
				ECHO "<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>變更工作人員資料<SPAN STYLE='COLOR:RED'>&nbsp;".$DATA['nickname']."</SPAN></TD></TR>
				<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>工作人員信箱</TD><TD><INPUT TYPE=TEXT NAME=EMAIL STYLE='WIDTH:250;FONT-SIZE:16' VALUE=".$DATA['email']."></TD></TR>
				<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>新登入密碼</TD><TD><INPUT TYPE=TEXT NAME=STFPASSWORD STYLE='WIDTH:250;FONT-SIZE:16'></TD></TR>";
				IF($_SESSION[LEVEL]=='admin')
				{
					IF($DATA['level']=='admin')
						ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>等　　級</TD><TD><INPUT TYPE=RADIO NAME=LEVEL VALUE='normal'>一般<INPUT TYPE=RADIO NAME=LEVEL VALUE='admin' CHECKED>管理員<INPUT TYPE=RADIO NAME=LEVEL VALUE='reg_admin'>地區管理員</TD></TR>";
					ELSE IF($DATA['level']=='reg_admin')
						ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>等　　級</TD><TD><INPUT TYPE=RADIO NAME=LEVEL VALUE='normal'>一般<INPUT TYPE=RADIO NAME=LEVEL VALUE='admin'>管理員<INPUT TYPE=RADIO NAME=LEVEL VALUE='reg_admin' CHECKED>地區管理員</TD></TR>";
					ELSE
						ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>等　　級</TD><TD><INPUT TYPE=RADIO NAME=LEVEL VALUE='normal' CHECKED>一般<INPUT TYPE=RADIO NAME=LEVEL VALUE='admin'>管理員<INPUT TYPE=RADIO NAME=LEVEL VALUE='reg_admin'>地區管理員</TD></TR>";
					ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>選　　區</TD><TD>";
					displayDistrict($DATA['elect_district_id']);
				}
				ELSE IF($_SESSION[LEVEL]=='reg_admin')
				{
					IF($DATA['level']=='reg_admin')
						ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>等　　級</TD><TD><INPUT TYPE=RADIO NAME=LEVEL VALUE='normal'>一般<INPUT TYPE=RADIO NAME=LEVEL VALUE='reg_admin' CHECKED>地區管理員</TD></TR>";
					ELSE
						ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>等　　級</TD><TD><INPUT TYPE=RADIO NAME=LEVEL VALUE='normal' CHECKED>一般<INPUT TYPE=RADIO NAME=LEVEL VALUE='reg_admin'>地區管理員</TD></TR>";
					ECHO "<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>選　　區</TD><TD>";
					displayDistrictRestricted($_SESSION['DISTRICT_ID']);
				}
				ECHO "</TD></TR>";
			}
			ECHO "
			<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>請輸入管理者代號及密碼</TD></TR>
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>管理者名稱</TD><TD><INPUT TYPE=TEXT NAME=NICKNAME STYLE='WIDTH:150;FONT-SIZE:16'></TD></TR>
			<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>管理者密碼</TD><TD><INPUT TYPE=PASSWORD NAME=PASSWORD STYLE='WIDTH:150;FONT-SIZE:16' VALUE=''></TD></TR>";
			IF($_GET['ACT']=="DELSTF")
			{
				ECHO "<TR><TD COLSPAN=2 ALIGN=CENTER><INPUT TYPE=BUTTON ONCLICK=history.go(-1) VALUE='取消'><INPUT TYPE=SUBMIT VALUE='刪除'></TD></TR>";
			}
			ELSE
			{
				ECHO "<TR><TD COLSPAN=2 ALIGN=CENTER><INPUT TYPE=BUTTON ONCLICK=history.go(-1) VALUE='取消'><INPUT TYPE=SUBMIT VALUE='修改'></TD></TR>";
			}
			ECHO "
			</TABLE>";
		}
		ELSE
		{
			ECHO "<BR>查無此資料<BR><BR><INPUT TYPE=BUTTON ONCLICK=history.go(-1) VALUE='回工作人員列表'><BR><BR>";
		}
	}
	ECHO "</TD></TR>";
}
ELSE IF($_GET['ACT']=="CPWD")
{
	ECHO "<TR><TD STYLE='BACKGROUND-COLOR:#EEEEEE;TEXT-ALIGN:CENTER;WIDTH:300'>";
	ECHO "
	<TABLE BORDER=0 STYLE='BACKGROUND-COLOR:#EEEEEE'>
		<FORM ACTION=processing_system.php?ACT=CPWDEXE METHOD=POST>
	<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>變更密碼</TD></TR>
	<TR><TD STYLE='TEXT-ALIGN:CENTER;WIDTH:150;BACKGROUND-COLOR:#DDDDDD'>舊　密　碼</TD><TD><INPUT TYPE=PASSWORD NAME=PASSWORD_O STYLE='WIDTH:150;FONT-SIZE:16'></TD></TR>
	<TR><TD STYLE='TEXT-ALIGN:CENTER;WIDTH:150;BACKGROUND-COLOR:#DDDDDD'>新　密　碼</TD><TD><INPUT TYPE=PASSWORD NAME=PASSWORD_N STYLE='WIDTH:150;FONT-SIZE:16'></TD></TR>
	<TR><TD STYLE='TEXT-ALIGN:CENTER;WIDTH:150;BACKGROUND-COLOR:#DDDDDD'>確認新密碼</TD><TD><INPUT TYPE=PASSWORD NAME=PASSWORD_R STYLE='WIDTH:150;FONT-SIZE:16'></TD></TR>
	<TR><TD COLSPAN=2 ALIGN=CENTER><BR><INPUT TYPE=SUBMIT VALUE='變更密碼' STYLE='FONT-SIZE:16'>
			</FORM><FORM ACTION=processing_system.php?ACT=LOGIN METHOD=POST>
				<INPUT TYPE=HIDDEN NAME=NICKNAME VALUE='".$_POST['NICKNAME']."'>
				<INPUT TYPE=HIDDEN NAME=PASSWORD VALUE='".$_POST['PASSWORD']."'>
				<INPUT TYPE=SUBMIT VALUE='取　　消' STYLE='FONT-SIZE:16'>
				</FORM>
		</TD></TR>
	</TABLE>
	";
	ECHO "</TD></TR>";
}
ELSE IF($_GET['ACT']=='CPWDEXE')
{
	ECHO "<TR><TD STYLE='BACKGROUND-COLOR:#EEEEEE;TEXT-ALIGN:CENTER;WIDTH:300'>";
	IF($_POST['PASSWORD_O']==""||$_POST['PASSWORD_N']==""||$_POST['PASSWORD_R']=="")
	{
		ECHO "<BR>所有欄位皆須填寫<BR><BR>";
		ECHO "<FORM ACTION=processing_system.php?ACT=CPWD METHOD=POST>
			<INPUT TYPE=SUBMIT VALUE='返回密碼修改頁面' STYLE='FONT-SIZE:16'>
			</FORM>";
	}
	ELSE IF($_POST['PASSWORD_O']!=$_POST['PASSWORD_N'])
	{
		IF($_POST['PASSWORD_N']==$_POST['PASSWORD_R'])
		{
			$QUERY_STRING="UPDATE STAFF_INFO SET PASSWORD=PASSWORD('".$_POST['PASSWORD_N']."') WHERE STAFF_ID='".$_SESSION['SID']."' AND PASSWORD=PASSWORD('".$_POST['PASSWORD_O']."')";
			IF(MYSQL_QUERY($QUERY_STRING)&&MYSQL_AFFECTED_ROWS()==1)
			{
				ECHO "<BR>密碼變更成功！<BR><BR>";
				ECHO "<FORM ACTION=processing_system.php?ACT=LOGIN METHOD=POST>
					<INPUT TYPE=SUBMIT VALUE='返回功能表' STYLE='FONT-SIZE:16'>
					</FORM>";
			}
			ELSE
			{
				ECHO "<BR>密碼變更失敗！<BR><BR>";
				ECHO "<FORM ACTION=processing_system.php?ACT=CPWD METHOD=POST>
					<INPUT TYPE=SUBMIT VALUE='返回密碼修改頁面' STYLE='FONT-SIZE:16'>
					</FORM>";
			}
		}
		ELSE
		{
			ECHO "<BR>新密碼未成功確認<BR><BR>";
			ECHO "<FORM ACTION=processing_system.php?ACT=CPWD METHOD=POST>
				<INPUT TYPE=SUBMIT VALUE='返回密碼修改頁面' STYLE='FONT-SIZE:16'>
				</FORM>";
		}
	}
	ELSE
	{
		ECHO "<BR>新舊密碼相同<BR>故資料未變更<BR>";
		ECHO "<FORM ACTION=processing_system.php?ACT=CPWD METHOD=POST>
			<INPUT TYPE=SUBMIT VALUE='返回密碼修改頁面' STYLE='FONT-SIZE:16'>
			</FORM>";
	}
	ECHO "</TD></TR>";
}
ELSE IF($_GET['ACT']==""||$_GET['ACT']=="LOGOUT")
{
	IF($_GET['ACT']=="LOGOUT")
	{
		$_SESSION['SID']="";
		$_SESSION['LEVEL']="";
		$_SESSION['NICKNAME']="";
		$_SESSION['DISTRICT_ID']="";
	}
	
	ECHO "
	<TR STYLE='VERTICAL-ALIGN:TOP'>
	<TD>
	<FORM ACTION=processing_system.php?ACT=LOGIN METHOD=POST>
	<TABLE BORDER=0 STYLE='BACKGROUND-COLOR:#EEEEEE'>
	<TR><TD COLSPAN=2 STYLE='TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#CCCCCC'>罷免工作人員登入</TD></TR>
	<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>使用者名稱</TD><TD><INPUT TYPE=TEXT NAME=NICKNAME STYLE='WIDTH:150;FONT-SIZE:16'></TD></TR>
	<TR><TD STYLE='WIDTH:150;TEXT-ALIGN:CENTER;BACKGROUND-COLOR:#DDDDDD'>密　　　碼</TD><TD><INPUT TYPE=PASSWORD NAME=PASSWORD STYLE='WIDTH:150;FONT-SIZE:16'></TD></TR>
	<TR><TD COLSPAN=2 ALIGN=CENTER><INPUT TYPE=SUBMIT VALUE='登入'></TD></TR>
	</TABLE>
	</FORM>
	</TD></TR>";
}
ECHO "</TABLE>";

FUNCTION displayDistrict($DEFAULT)
{
	$QUERY_STRING="SELECT * FROM DISTRICT_DATA";
	$NO_OF_DATA=MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING));
	ECHO "<SELECT NAME=DISTRICT_ID STYLE='WIDTH:250;HEIGHT:30;FONT-SIZE:16'>";
	ECHO "<OPTION VALUE=''>請選擇選區</OPTION>";
	FOR($SEED=0;$SEED<$NO_OF_DATA;$SEED++)
	{
		$DATA=MYSQL_FETCH_ARRAY($RESULT);
		ECHO "<OPTION VALUE='".$DATA['district_id']."' ";
		IF($DATA['district_id']==$DEFAULT)
			ECHO "SELECTED";
		ECHO ">".$DATA['district_name']."．".$DATA['district_legislator']."</OPTION>";
	}
	ECHO "</SELECT>";
}

FUNCTION displayDistrictRestricted($DEFAULT)
{
	$QUERY_STRING="SELECT * FROM DISTRICT_DATA WHERE DISTRICT_ID='".$DEFAULT."'";
	IF($RESULT=MYSQL_QUERY($QUERY_STRING))
		$DATA=MYSQL_FETCH_ARRAY($RESULT);
	ECHO "<SELECT NAME=DISTRICT_ID STYLE='WIDTH:250;HEIGHT:30;FONT-SIZE:16'>";
	ECHO "<OPTION VALUE='".$DEFAULT."' SELECTED>".$DATA['district_name']."．".$DATA['district_legislator']."</OPTION>";
	ECHO "</SELECT>";
}


?>
</CENTER>